### ISSUE TITLE
Merge support

### ISSUE THREAD

**Issue by coderaiser** [fabiospampinato/fast-ignore#1]
Could you please tell me is merge supported? [Similar to this one](https://github.com/kaelzhang/node-ignore/issues/107#issuecomment-1827672473):

```sh
tmp
**/coverage
!**/coverage
```

It was merged to:

```sh
tmp
```

**Comment by fabiospampinato** [comment]
If I'm understanding what you are asking for: ignore files are not optimized to remove kinda self-cancelling rules like that, but if you repeat those 2 lines 1 million times they won't slow down matching because they end up populating the same nodes internally, like they kinda overwrite each other, so I guess there is some kind of implicit merging.

**Comment by coderaiser** [comment]
I’m talking not about slowdown, but about overriding ignore. It useful when something was ignored by default and you want to stop ignoring it. How it will work right now for such case:
```
**/coverage
!**/coverage
```

`coverage` is ignored or not when it used by your library?

**Comment by fabiospampinato** [comment]
Coverage would be not ignored in that scenario with this library. Unless the library is buggy we try to parse ignore files like git would.

**Comment by coderaiser** [comment]
OK, I tried it, it works good:

```
**/coverage
!**/coverage
```

`coverage` ignored and:

```
!**/coverage
**/coverage
```

`coverage` not ignored. Is it possible to produce CommonJS? I need to use this library inside **ESLint** plugin which is sync CommonJS only.

**Comment by fabiospampinato** [comment]
Sorry I've moved fully to ESM to avoid all the complications with supporting both at the same time. You can bundle it to CJS inside your package or something if you really need to import it synchronously 🤔
